proxy_pass http://unix:/run/webui-@SERVICE@/auth.sock;
proxy_pass_request_headers off;
proxy_set_header Host $http_host;
proxy_set_header Content-Type $http_content_type;
proxy_set_header Cookie $@COOKIE_VARIABLE@;
proxy_set_header Origin $http_origin;
proxy_set_header X-Original-Method $request_method;
proxy_set_header X-Original-Origin $http_origin;
